### ISSUE TITLE
SSLCertVerificationError

### ISSUE THREAD

**Issue by Mike-Honey** [ronentk/sci-paper-miner#1]
I'm getting this error:

  File "C:\Users\mikehoney\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

I wasn't able to use the exact requirements.txt due to version conflicts. I installed the latest version of each requirement manually.

**Comment by Mohamad-Alomari** [comment]
`Saving query to  /Users/mohamadalomari/Desktop/sci-paper-miner-master/data/arxiv_2006-2017_cs/raw_query... (This may take a while)
  0%|                                                    | 0/33 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "crawl_core.py", line 40, in <module>
    core_req.handle_query(configs.core_cs_query_path, query_params, core_requestor.SEARCH_METHOD)
  File "/Users/mohamadalomari/Desktop/sci-paper-miner-master/core_requestor.py", line 112, in handle_query
    pages = self.get_base_query(method, sub_query_string, fulltext=True)
  File "/Users/mohamadalomari/Desktop/sci-paper-miner-master/core_requestor.py", line 79, in get_base_query
    print("\rFetching %d papers..." % (result['totalHits'])),`
